# Generated by Django 5.0 on 2023-12-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Clama.producto')),
                ('codigo_calzado', models.CharField(default='N/A', max_length=50, unique=True)),
                ('talla', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
            ],
            bases=('Clama.producto',),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='codigo_camiseta',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='codigo_pantalon',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
        ),
    ]
