# Generated by Django 5.0 on 2023-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clama', '0002_calzado_camiseta_codigo_camiseta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
